name: Update translations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  translations:
    uses: InsanityGod/InsanityLib/.github/workflows/update-translations.yml@master
    with:
      MOD_LANG_PATH: "BrainFreeze/assets/brainfreeze/lang"
      TRANSLATION_ZIP: "brainfreeze-theinsanitygod.zip"
